springdoc:
  swagger-ui:
    persist-authorization: false
  api-docs:
    path: /v3/api-docs/sys
#spring:
#  web:
#    cors:
#      allowed-origins: "http://localhost:8080"
#      allowed-methods: "*"
#      allowed-headers: "*"
#      allow-credentials: true
spring:
  redis:
    host: localhost
    port: 6379

chat:
  enabled: true
  max-message-size: 4096