server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:63342"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service-auth-route
          uri: lb://sys-srv
          predicates:
            - Path=/auth/**

        - id: auth-service-users-route
          uri: lb://sys-srv
          predicates:
            - Path=/users/**

        - id: medical-record-service-route
          uri: lb://medical-record-service
          predicates:
            - Path=/services/**

        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
          - Path=/appointments/**

        - id: appointment-service-reviews-route
          uri: lb://appointment-service
          predicates:
            - Path=/reviews/**

        - id: medical-record-service--protocols-route
          uri: lb://medical-record-service
          predicates:
            - Path=/protocols/**

        - id: auth-service-branches-route
          uri: lb://sys-srv
          predicates:
            - Path=/branches/**

        - id: product-inventory-service-route
          uri: lb://product-inventory-service
          predicates:
            - Path=/products/**

        - id: product-inventory-service-inventory-route
          uri: lb://product-inventory-service
          predicates:
            - Path=/inventory/**

        - id: medical-record-service-records-route
          uri: lb://medical-record-service
          predicates:
            - Path=/medical-records/**

        - id: medical-record-service-service-material-route
          uri: lb://medical-record-service
          predicates:
            - Path=/service-materials/**

        - id: medical-record-service-service-templates
          uri: lb://medical-record-service
          predicates:
            - Path=/templates/**

        - id: reporting-service-route
          uri: lb://reporting-service
          predicates:
            - Path=/reports/**

        - id: auth-service-profiles-route
          uri: lb://sys-srv
          predicates:
            - Path=/patient-profiles/**

        - id: appointment-service-protocol-tracking-route
          uri: lb://appointment-service
          predicates:
            - Path=/protocol-tracking/**

        - id: appointment-service-payment
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/**

        - id: appointment-service-available-slots
          uri: lb://appointment-service
          predicates:
            - Path=/slots/**

        - id: auth-service-doctor-profiles-route
          uri: lb://sys-srv
          predicates:
            - Path=/doctor-profiles/**

        - id: chatbot-service-chat
          uri: http://localhost:8000
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=0

        - id: chatbot-service-health
          uri: http://localhost:8000
          predicates:
            - Path=/health
          filters:
            - StripPrefix=0

        - id: medical-record-service-service-bill
          uri: lb://medical-record-service
          predicates:
            - Path=/bills/**

        - id: sys-srv-ws-chat
          uri: lb://sys-srv   # <-- sửa thành host:port thật của sys-srv (ws:// or wss://)
          predicates:
            - Path=/ws-chat/**       # bao gồm /ws-chat/info và tất cả transport của SockJS
          filters:
            - StripPrefix=0

        - id: sys-srv-chat-api
          uri: lb://sys-srv      # hoặc http://localhost:8081 nếu không dùng Eureka
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka